### ISSUE TITLE
CCTextField issue with Android: ShowKeyboardInput

### ISSUE THREAD

**Issue by Heikofant** [mono/CocosSharp#333] opened 2015-12-07 18:41 UTC
Hey,

I experienced several crashes with the latest release of `CCTextField`

Unfortunately, the crashes occured on remote testing devices so I don't know why and when they occured, but here are the crash reports:

```
System.NullReferenceExceptionObject reference not set to an instance of an object
CocosSharp.IMEKeyboardImpl.ShowKeyboardInput(string defaultText)
CocosSharp.IMEKeyboardImpl.<>c__DisplayClassa.<ShowKeyboardAsync>b__8()
System.Threading.Tasks.Task<TResult>.InnerInvoke()
System.Threading.Tasks.Task.Execute()
```
and
```
System.AggregateExceptionA Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.
Raw
TIL.Droid.src.Activities.App.OnException()
System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(object state)
System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, object state, bool preserveSyncCtx)
System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, object state, bool preserveSyncCtx)
System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
System.Threading.ThreadPoolWorkQueue.Dispatch()
System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

It occured so far on the following devices:
google Nexus 4 (Android 5.1)
Amazon KFMEWI  (Android 5.1)
samsung GT-N8010 (Android 4.1.1)

**Comment by kjpou1** [comment] 2015-12-08 04:57
Heikofant

We are probably going to need a little more information.  Have you been able to try on those devices yourself?  Can we get a small project with the exact code you are setting up the CCTextField and actually calling this with?

**Comment by kjpou1** [comment] 2015-12-08 05:08
Oh I see those are all relative new just come out devices.  I actually have a Galaxy Note here that I use for testing so not sure what the problem would be there.  Still would be necessary a small project as stated previously.

**Comment by Heikofant** [comment] 2015-12-08 10:08
Project is attached. It's just a layer to login with two CCTextField (I stripped it down for the upload)


I could not reproduce the errors as I don't have access to those devices.

The devices are not very recent (just the Amazon Fire).

[CCTextFieldCrash.zip](https://github.com/mono/CocosSharp/files/55244/CCTextFieldCrash.zip)

**Comment by kjpou1** [comment] 2015-12-08 10:32
Ok, this has tested out on three real devices and of course the plethera of simulators.

Can you make it crash?  Without recreating the error itself we really can not do much.  A little more help tracking down the error will be needed.

**Comment by Heikofant** [comment] 2015-12-08 10:39
same for me. 
I can't reproduce the error at the moment (genymotion emulators and samsung SM-T805)
 
As I said, I don't have access to the devices where the error occurs. 
Hopefully I'm getting more informations soon.

Thanks for reacting so fast!

**Comment by rtabbara** [comment] 2015-12-19 13:53
@Heikofant I have also tested this out on both devices and simulators and am unable to reproduce the reported issue.

Will close this for now, however if you are able to replicate the error observed please let us know.

**Closed by rtabbara** 2015-12-19 13:53 UTC
